# Generated by Django 2.2.24 on 2025-02-04 16:12

from django.db import migrations
from ..models import Flat


def update_new_building(apps, schema_editor):
    Flat = apps.get_model("property", "Flat")

    # Обновляем все квартиры, построенные после 2014 года
    Flat.objects.filter(construction_year__gt=2014).update(new_building=True)

    # Обновляем остальные квартиры
    Flat.objects.exclude(construction_year__gt=2014).update(new_building=False)


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_flat_new_building'),
    ]

    operations = [
        migrations.RunPython(update_new_building)
    ]
