# Generated by Django 2.2.24 on 2025-02-04 16:12

from django.db import migrations
from ..models import Flat


def update_new_building(apps, schema_editor):
    Flat = apps.get_model("property", "Flat")  # Получаем модель через ORM миграции

    for flat in Flat.objects.all():  # Проходимся по всем объектам Flat
        if flat.construction_year and flat.construction_year > 2014:
            flat.new_building = True
        else:
            flat.new_building = False

        flat.save()  # Сохраняем изменения для каждого объекта


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_flat_new_building'),
    ]

    operations = [
        migrations.RunPython(update_new_building)
    ]
