# Generated by Django 2.2.24 on 2025-01-12 17:34

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0006_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='flat',
            name='owner_pure_phobne',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='Форматированный номер владельца'),
        ),
    ]
