# Generated by Django 2.2.24 on 2025-02-04 17:44

from django.db import migrations
import phonenumbers


def normalize_phone_numbers(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    flats = Flat.objects.all()
    for flat in flats:
        try:
            # Парсим номер
            parsed_number = phonenumbers.parse(flat.owners_phonenumber, "RU")
            if phonenumbers.is_valid_number(parsed_number):
                # Если номер валиден, форматируем в E164
                formatted_phone = phonenumbers.format_number(
                    parsed_number, phonenumbers.PhoneNumberFormat.E164
                )
            else:
                # Если номер невалиден
                formatted_phone = None
        except phonenumbers.NumberParseException:
            # Если номер не удалось разобрать
            formatted_phone = None
        # Обновляем только поле owner_pure_phone
        Flat.objects.filter(id=flat.id).update(owner_pure_phone=formatted_phone)


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0007_auto_20250204_2040'),
    ]

    operations = [
    ]
