# Generated by Django 2.2.24 on 2025-01-12 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0007_flat_owner_pure_phobne'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flat',
            old_name='owner_pure_phobne',
            new_name='owner_pure_phone',
        ),
        migrations.DeleteModel(
            name='Owner',
        ),
    ]
