# Generated by Django 2.2.24 on 2025-01-12 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0010_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='flats',
            field=models.ManyToManyField(blank=True, related_name='owners_list', to='property.Flat', verbose_name='Квартиры в собственности'),
        ),
    ]
