# Generated by Django 2.2.24 on 2025-01-12 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0012_transfer_owners_to_model'),
        ('property', '0011_auto_20250112_2117'),
    ]

    operations = [
    ]
