# Generated by Django 2.2.24 on 2025-02-04 18:14

from django.db import migrations


def fill_owner_card(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')
    for flat in Flat.objects.all():
        Owner.objects.get_or_create(owner=flat.owner, owners_phonenumber=flat.owners_phonenumber, owner_phone_pure=flat.owner_pure_phone)


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0012_auto_20250204_2107'),
    ]

    operations = [
        migrations.RunPython(fill_owner_card)
    ]
