# Generated by Django 2.2.24 on 2025-02-04 19:03

from django.db import migrations


def clear_owned_property(apps, schema_editor):
    Owner = apps.get_model('property', 'Owner')
    Flat = apps.get_model('property', 'Flat')

    for owner in Owner.objects.all():
        owner.owned_property.clear()
        owner.save()


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0015_auto_20250204_2127'),
    ]

    operations = [
        migrations.RunPython(clear_owned_property)
    ]
