# Generated by Django 2.2.24 on 2025-02-04 20:05

from django.db import migrations


def fix_owned_flats(apps, schema_editor):
    Owner = apps.get_model("property", "Owner")
    Flat = apps.get_model("property", "Flat")

    # Очистка всех связей
    for owner in Owner.objects.all():
        owner.owned_property.clear()

    # Восстановление корректных связей
    for owner in Owner.objects.all():
        flats = Flat.objects.filter(owner=owner.owner, owners_phonenumber=owner.owners_phonenumber)
        owner.owned_property.set(flats)  # Устанавливаем правильные квартиры


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0017_auto_20250204_2210'),
    ]

    operations = [
        migrations.RunPython(fix_owned_flats)
    ]
