# Generated by Django 2.2.24 on 2025-02-05 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0019_fix_owned_flats1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flat',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='flat',
            name='owner_pure_phone',
        ),
        migrations.RemoveField(
            model_name='flat',
            name='owners_phonenumber',
        ),
    ]
