# Generated by Django 2.2.24 on 2025-02-05 10:16
import phonenumbers
from django.db import migrations


def normalize_phone_numbers(apps, schema_editor):
    Owner = apps.get_model('property', 'Owner')
    Owners = Owner.objects.all()
    for owner in Owners:
        try:
            # Парсим номер
            parsed_number = phonenumbers.parse(owner.owners_phonenumber, "RU")
            if phonenumbers.is_valid_number(parsed_number):
                # Если номер валиден, форматируем в E164
                formatted_phone = phonenumbers.format_number(
                    parsed_number, phonenumbers.PhoneNumberFormat.E164
                )
            else:
                # Если номер невалиден
                formatted_phone = None
        except phonenumbers.NumberParseException:
            # Если номер не удалось разобрать
            formatted_phone = None
        # Обновляем только поле owner_pure_phone
        Owner.objects.filter(id=owner.id).update(owner_phone_pure=formatted_phone)


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0020_auto_20250205_1311'),
    ]

    operations = [
        migrations.RunPython(normalize_phone_numbers)
    ]
