# Generated by Django 4.2.19 on 2025-02-09 13:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('property', '0022_alter_complaint_id_alter_flat_has_balcony_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='owner',
            old_name='owner',
            new_name='fio',
        ),
        migrations.RenameField(
            model_name='owner',
            old_name='owners_phonenumber',
            new_name='phonenum',
        ),
        migrations.RenameField(
            model_name='owner',
            old_name='owner_phone_pure',
            new_name='phonenum_pure',
        ),
        migrations.RenameField(
            model_name='owner',
            old_name='owned_property',
            new_name='property',
        ),
        migrations.AlterField(
            model_name='flat',
            name='likes',
            field=models.ManyToManyField(blank=True, db_index=True, related_name='who_liked', to=settings.AUTH_USER_MODEL, verbose_name='Кто лайкнул'),
        ),
    ]
