# Generated by Django 4.2.19 on 2025-02-16 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0025_rename_property_owner_properties'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='properties',
            field=models.ManyToManyField(blank=True, related_name='owners', to='property.flat', verbose_name='Квартиры в собственности'),
        ),
    ]
